#!/bin/bash
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_connect | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_disconnect  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_disk_free  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_quota  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_set_quota  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_shadow_copy_data  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_statvfs  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fs_capabilities  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_dfs_referrals  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_opendir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fdopendir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_readdir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_seekdir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_telldir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_mkdir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_rmdir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_closedir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_open  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_create_file  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_close  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_pread  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_pwrite  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_lseek  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sendfile  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_recvfile  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_rename  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fsync  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_stat  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fstat  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_lstat  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_alloc_size  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_unlink  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_chmod  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fchmod  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_chown  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fchown  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_lchown  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_chdir  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_getwd  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_ntimes  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_ftruncate  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fallocate  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_lock  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_kernel_flock  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_linux_setlease  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_getlock  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_symlink  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_readlink  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_link  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_mknod  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_realpath  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_chflags  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_file_id_create  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_offload_read_send  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_offload_read_recv  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_offload_write_send  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_offload_write_recv  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_compression  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_set_compression  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_snap_check_path  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_snap_create  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_snap_delete  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_streaminfo  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_real_filename  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_connectpath  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_brl_lock_windows  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_brl_unlock_windows  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_brl_cancel_windows  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_strict_lock_check  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_translate_name  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fsctl  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_dos_attributes  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fget_dos_attributes  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_set_dos_attributes  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fset_dos_attributes  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fget_nt_acl  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_get_nt_acl  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fset_nt_acl  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_audit_file  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_get_file  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_get_fd  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_blob_get_file  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_blob_get_fd  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_set_file  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_set_fd  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_sys_acl_delete_def_file  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_getxattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fgetxattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_listxattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_flistxattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_removexattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fremovexattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_setxattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_fsetxattr  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_aio_force  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_durable_cookie  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_durable_disconnect  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_durable_reconnect  | wc -l
cat windows.samba.aio_fork.aio_pthread.lttng.log | grep vfs_lttng_readdir_attr  | wc -l
